name: datalines
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

      #
    #  # The following adds the Cupertino Icons font to your application.
    #  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  hive: ^2.0.6
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  hive_flutter: ^1.1.0
  bloc:
  equatable: ^2.0.3
  flutter_bloc:
  multi_select_flutter: ^4.1.2
  file_picker: ^4.5.1
  flutter_local_notifications: ^9.4.0
  downloads_path_provider_28: ^0.1.2
  open_file: ^3.2.1
  awesome_notifications: ^0.6.21
  cool_alert: ^1.1.0
  flutter_rating_bar: ^4.0.1
  get_it: ^7.2.0
  easy_localization: ^3.0.0
  flutter_svg: ^1.0.3
  dio: ^4.0.6
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  analyzer: ^2.3.0
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+3
  pretty_dio_logger: ^1.2.0-beta-1
  shared_preferences: ^2.0.15
  freezed: ^1.1.0
  flutter_screenutil: ^5.5.3+2
  flutter_spinkit: ^5.1.0
  percent_indicator: ^4.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animation/
    - assets/languages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300